<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-9GECL9UO" failures="1" tests="3" name="Test" time="33.866" errors="0" timestamp="2024-12-19T23:27:00 IST">
  <testcase classname="testCases.TC103_ContactAdditionTest" name="testContactListMandatoryfileds" time="12.211"/>
  <testcase classname="testCases.TC103_ContactAdditionTest" name="testContactListoptionalfileds" time="6.903"/>
  <testcase classname="testCases.TC103_ContactAdditionTest" name="duplicateContactList" time="11.283">
    <failure type="java.lang.AssertionError" message="Expected error message for duplicate contact, but got:  expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected error message for duplicate contact, but got:  expected [true] but found [false]
at testCases.TC103_ContactAdditionTest.duplicateContactList(TC103_ContactAdditionTest.java:97)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- duplicateContactList -->
</testsuite> <!-- Test -->
